/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131318",
        "on-primary": "#003060",
        "primary-fixed": "#d5e3ff",
        "surface-container-lowest": "#0e0e13",
        "surface-container": "#1f1f25",
        "inverse-surface": "#e4e1e9",
        "on-error": "#690005",
        "outline": "#8b919e",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#27e199",
        "on-secondary-fixed-variant": "#005234",
        "on-secondary-container": "#005737",
        "on-primary-fixed": "#001b3c",
        "tertiary-container": "#fc6969",
        "on-surface-variant": "#c1c6d5",
        "surface-tint": "#a7c8ff",
        "surface-variant": "#35343a",
        "error-container": "#93000a",
        "secondary-fixed": "#54feb3",
        "surface": "#131318",
        "on-secondary-fixed": "#002112",
        "surface-container-highest": "#35343a",
        "secondary-container": "#00d68f",
        "on-tertiary": "#68000f",
        "tertiary-fixed-dim": "#ffb3b0",
        "primary-container": "#4c9aff",
        "secondary": "#44f3a9",
        "surface-container-low": "#1b1b20",
        "background": "#131318",
        "on-primary-fixed-variant": "#004788",
        "on-tertiary-container": "#6a0010",
        "error": "#ffb4ab",
        "on-background": "#e4e1e9",
        "surface-bright": "#39383e",
        "inverse-primary": "#005eb2",
        "on-secondary": "#003822",
        "tertiary": "#ffb3b0",
        "on-primary-container": "#003162",
        "tertiary-fixed": "#ffdad8",
        "surface-container-high": "#2a292f",
        "outline-variant": "#414753",
        "primary": "#a7c8ff",
        "on-surface": "#e4e1e9",
        "on-tertiary-fixed-variant": "#8c1520",
        "on-tertiary-fixed": "#410006",
        "primary-fixed-dim": "#a7c8ff",
        "inverse-on-surface": "#303036"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "2rem",
        "base": "4px",
        "md": "1.5rem",
        "xl": "3rem",
        "xs": "0.5rem",
        "sm": "1rem",
        "margin-desktop": "2.5rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "tabular-nums": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "tabular-nums": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
